feat: Integration Training Event Filter Table
jeheskielSunloy77/dataon-project pull request #26
Opened 2022-09-05 12:05 UTC by jeheskielSunloy77

Search Filters demo
https://user-images.githubusercontent.com/38202065/188445282-fc846b84-3f93-498d-af3e-4d4cbc11ce66.mp4

2022-09-06 04:23 UTC, argorfc commented on src/pages/Home/sections/AllTrainings/index.jsx
> +	const url = `trainings?${
move the constant into utils function to serialize query params dynamically

2022-09-06 04:23 UTC, argorfc commented on src/pages/Home/sections/MyTraining/index.jsx
> +	const url = `trainings?${
move the constant into utils function to serialize query params dynamically

2022-09-06 04:25 UTC, argorfc requested changes
Challenges today, remove duplicate code.

2022-09-06 07:31 UTC, jeheskielSunloy77 commented
@argorfc i have update the pull request

2022-09-07 13:02 UTC, argorfc approved these changes
Approved.

2022-09-07 13:07 UTC, argorfc requested changes
Need update the query params

2022-09-08 01:54 UTC, jeheskielSunloy77 commented
@argorfc i have update the pull request and have change the queryParams function

2022-09-08 02:02 UTC, argorfc approved these changes
Approved

2022-09-08 02:36 UTC, merged