feat: Table Section and Breadcrum Unit test
jeheskielSunloy77/dataon-project pull request #8
Opened 2022-08-16 12:37 UTC by jeheskielSunloy77

1. Adding Table component on home page
2. Table data sorting
3. Breadcrumb and create new training unit test

Table section
![Screenshot from 2022-08-16 19-33-34](https://user-images.githubusercontent.com/38202065/184880651-a75d0a3e-bc86-4539-b242-c95d94033530.png)
Unit testing result
![Screenshot from 2022-08-16 19-35-00](https://user-images.githubusercontent.com/38202065/184880996-7f4521db-709e-4a54-846a-1b15014df800.png)

2022-08-16 13:05 UTC, argorfc commented on src/pages/Home/TableSection.jsx
> +const RatingScore = ({ score }) => {
Please movie into component folder, it should be a reusable component.

2022-08-16 13:05 UTC, argorfc commented on src/pages/Home/TableSection.jsx
> +const StarIcon = ({ active }) => (
Please movie into component folder, it should be a reusable component.

2022-08-16 13:06 UTC, argorfc commented on src/pages/Home/TableSection.jsx
> +	<svg
create component icon, it can help for another icon

2022-08-16 13:06 UTC, argorfc requested changes
Please read comments!

2022-08-16 14:17 UTC, jeheskielSunloy77 commented
@argorfc i have made some changes and i have move TableData, RatingScore and StarIcons to their own component file.
thank you for the review

2022-08-18 02:03 UTC, argorfc reviewed
What is difference between src/components/StarIcon.jsx with  src/components/icons/StarIcon.jsx ?

2022-08-18 02:26 UTC, jeheskielSunloy77 commented
@argorfc Sorry for my mistake, I have deleted the file and the redundancy has been resolved.

2022-08-18 02:42 UTC, argorfc approved these changes
Approved.
Ready to merge.

2022-08-18 02:58 UTC, merged